# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
  - CODECOV_TOKEN="5068567b-5d80-4b3b-b672-32c6193ed3d4"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - zheniog@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always